apiVersion: v1
kind: Service
metadata:
  name: {{ include "streaming-app.fullname" . }}-helloservice
  labels:
    {{- include "streaming-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.helloService.service.type }}
  ports:
    - port: {{ .Values.helloService.service.port }}
      targetPort: {{ .Values.helloService.port }}
  selector:
    {{- include "streaming-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: helloservice