{{- if .Values.helloService.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "streaming-app.fullname" . }}-helloservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "streaming-app.fullname" . }}-helloservice
  minReplicas: {{ .Values.helloService.hpa.minReplicas }}
  maxReplicas: {{ .Values.helloService.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.helloService.hpa.targetCPUUtilizationPercentage }}
{{- end }}
---
{{- if .Values.profileService.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "streaming-app.fullname" . }}-profileservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "streaming-app.fullname" . }}-profileservice
  minReplicas: {{ .Values.profileService.hpa.minReplicas }}
  maxReplicas: {{ .Values.profileService.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.profileService.hpa.targetCPUUtilizationPercentage }}
{{- end }}
---
{{- if .Values.frontend.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "streaming-app.fullname" . }}-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "streaming-app.fullname" . }}-frontend
  minReplicas: {{ .Values.frontend.hpa.minReplicas }}
  maxReplicas: {{ .Values.frontend.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontend.hpa.targetCPUUtilizationPercentage }}
{{- end }}
